# Generated by Django 5.2 on 2025-04-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_processing',
            field=models.BooleanField(default=True),
        ),
    ]
