# Generated by Django 5.2 on 2025-04-14 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_is_processing'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.genre')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.video')),
            ],
            options={
                'verbose_name': 'Video Genre',
                'verbose_name_plural': 'Video Genres',
                'db_table': 'video_genres',
                'unique_together': {('video', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='video',
            name='genres',
            field=models.ManyToManyField(related_name='videos', through='content.VideoGenre', to='content.genre'),
        ),
    ]
